service: frontend
runtime: python39
env: standard

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|png|jpg|svg|json|ico|map))
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|svg|json|ico|map)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
